config/routes.rb
Mp3App::Application.routes.draw do
    match "songs/upload", :as => "upload"  
    match "songs/delete", :as => "delete"  
      
    root :to => "songs#index"  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/songs_controller.rb
  
   require 'aws/s3'
   BUCKET = ''

   class SongsController < ApplicationController  
      def index  
        @songs = AWS::S3::Bucket.find(BUCKET).objects  
      end  
      
      def upload  
        begin  
          AWS::S3::S3Object.store(sanitize_filename(params[:mp3file].original_filename), params[:mp3file].read, BUCKET, :access => :public_read)  
          redirect_to root_path  
        rescue  
          render :text => "Couldn't complete the upload"  
        end  
      end  
      
      def delete  
        if (params[:song])  
          AWS::S3::S3Object.find(params[:song], BUCKET).delete  
          redirect_to root_path  
        else  
          render :text => "No song was found to delete!"  
        end  
      end  
      
      private  
      
      def sanitize_filename(file_name)  
        just_filename = File.basename(file_name)  
        just_filename.sub(/[^\w\.\-]/,'_')  
      end  

      

   end

app/helpers/application_helper.rb
module ApplicationHelper
end


def download_url_for(song_key)  
    AWS::S3::S3Object.url_for(song_key, BUCKET, :authenticated => false)  
 end

     def torrent_url_for(song_key)  
        download_url_for(song_key) + "?torrent"  
    end  

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mp3App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js" %> 
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
<%= yield %>
</div>

</body>
</html>

app/views/songs/index.html.erb
<header>  
  <h1>My First Music Streaming Application</h1>  
</header> 

    <div class="clear"></div>  
    <section id="sidebar">  
        <h2>HTML5 Audio</h2>  
        <section id="audio">  
            No song is currently playing.  
        </section>  
      
        <h2>Upload a Song</h2>  
        <%= form_tag upload_path, :method => "post", :multipart => true do %>  
            <%= file_field_tag "mp3file" %><br />  
            <%= submit_tag "Upload" %>  
        <% end %>  
    </section>  
    <section id="main">  
        <h2>Download/Delete Songs</h2>  
        <table>  
        <% @songs.each do |song| %>  
            <tr>  
                <td><%= song.key %></td>  
                <td><%= link_to "HTML5 Audio", download_url_for(song.key), :class => "html5" %></td>  
                <td><%= link_to "Download", download_url_for(song.key) %></td>  
                <td><%= link_to "Torrent", torrent_url_for(song.key) %></td>  
                <td><%= link_to "Delete",  "songs/delete/?song=" + song.key, :confirm => 'Are you sure you want to delete ' + song.key + '?' %></td>  
            </tr>  
        <% end %>  
        </table>  
    </section>  
    <div class="clear"></div> 